# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(657, 469)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor)) #暂时没发现此代码的用处。
        self.userLable = QtWidgets.QLabel(Form)
        self.userLable.setGeometry(QtCore.QRect(60, 70, 91, 41))
        self.userLable.setObjectName("userLable")
        self.pwdLable = QtWidgets.QLabel(Form)
        self.pwdLable.setGeometry(QtCore.QRect(60, 140, 91, 41))
        self.pwdLable.setObjectName("pwdLable")
        self.userEdit = QtWidgets.QLineEdit(Form)
        self.userEdit.setGeometry(QtCore.QRect(140, 80, 131, 31))
        self.userEdit.setObjectName("userEdit")
        self.pwdEdit = QtWidgets.QLineEdit(Form)
        self.pwdEdit.setGeometry(QtCore.QRect(140, 150, 131, 31))
        self.pwdEdit.setObjectName("pwdEdit")
        self.login = QtWidgets.QPushButton(Form)
        self.login.setGeometry(QtCore.QRect(70, 280, 93, 28))
        self.login.setObjectName("login")
        self.layout = QtWidgets.QPushButton(Form)
        self.layout.setGeometry(QtCore.QRect(200, 280, 93, 28))
        self.layout.setObjectName("layout")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(325, 81, 281, 221))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "用户登录"))
        self.userLable.setText(_translate("Form", "用户名"))
        self.pwdLable.setText(_translate("Form", "密码"))
        self.login.setText(_translate("Form", "登录"))
        self.layout.setText(_translate("Form", "退出"))
